GET https://127.0.0.1:8002/api/v1/catalog/xml
###
GET https://irely.hris.hordeflow.com/api/v1/customer
###
GET https://hordeflow.hris.hordeflow.com/api/v1/customer
###
GET https://xyz.hris.hordeflow.com/api/v1/customer
###
GET https://localhost:8000/api/v1/customer
Accept: application/xml
###
GET https://localhost:8002/api/v1/customer
###
GET https://localhost:8000/health
###
GET https://localhost:8003/api/v1/tenant