@url = https://localhost
@dns = hris.hordeflow.com
###
GET {{url}}:8003/api/v1/admin/catalog
###
GET {{url}}:8001/api/v1/admin/catalog/xml
###
GET https://irely.{{dns}}/api/v1/customer
###
###
GET https://irely.{{dns}}/api/v1/customer
###
GET https://hordeflow.{{dns}}/api/v1/customer
###
GET https://xyz.{{dns}}/api/v1/customer
###
GET {{url}}:8001/api/v1/customer
Accept: application/xml
###
GET {{url}}:8002/api/v1/customer
###
GET {{url}}:8000/health
###
GET https://irely.{{dns}}/api/v1/tenant