// <auto-generated />
using System;
using HordeFlow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HordeFlow.Migrations.Sqlite
{
    [DbContext(typeof(TenantSqliteDbContext))]
    [Migration("20191122133033_SqliteMigration")]
    partial class SqliteMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("HordeFlow.Models.tblARCustomer", b =>
                {
                    b.Property<int>("intEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("ConcurrencyTimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("dblARBalance")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("dblCreditLimit")
                        .HasColumnType("TEXT");

                    b.Property<string>("strAccountNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("strCurrency")
                        .HasColumnType("TEXT");

                    b.Property<string>("strCustomerNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("strTaxNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("strType")
                        .HasColumnType("TEXT");

                    b.HasKey("intEntityId");

                    b.ToTable("tblARCustomer");
                });

            modelBuilder.Entity("HordeFlow.Models.tblSMCompanyLocation", b =>
                {
                    b.Property<int>("intCompanyLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("strAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("strCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("strCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("strEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("strFax")
                        .HasColumnType("TEXT");

                    b.Property<string>("strLocationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("strLocationNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("strLocationType")
                        .HasColumnType("TEXT");

                    b.Property<string>("strPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("strStateProvince")
                        .HasColumnType("TEXT");

                    b.Property<string>("strWebsite")
                        .HasColumnType("TEXT");

                    b.Property<string>("strZipPostalCode")
                        .HasColumnType("TEXT");

                    b.HasKey("intCompanyLocationId");

                    b.ToTable("tblSMCompanyLocation");
                });
#pragma warning restore 612, 618
        }
    }
}
