// <auto-generated />
using System;
using HordeFlow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HordeFlow.Migrations.SqlServer
{
    [DbContext(typeof(TenantSqlServerDbContext))]
    [Migration("20191122133011_SqlServerMigration")]
    partial class SqlServerMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HordeFlow.Models.tblARCustomer", b =>
                {
                    b.Property<int>("intEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("ConcurrencyTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("dblARBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("dblCreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("strAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strCustomerNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strTaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("intEntityId");

                    b.ToTable("tblARCustomer");
                });

            modelBuilder.Entity("HordeFlow.Models.tblSMCompanyLocation", b =>
                {
                    b.Property<int>("intCompanyLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("strAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strLocationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strLocationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strLocationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strStateProvince")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strZipPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("intCompanyLocationId");

                    b.ToTable("tblSMCompanyLocation");
                });
#pragma warning restore 612, 618
        }
    }
}
